name: $(Date:yyyyMMdd)$(Rev:.r)-App-CI

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - motivational-app/*

pool:
  name: 'Self hosted pools'
  demands:
   - Agent.Name -equals alaaynassar-VMware

variables:
  - group: 'My Vars'
  - name: ECR_REPOSITORY_NAME
    value: 'alaa-devops-project-repo' 

steps:
- checkout: self

# 1. Login to AWS ECR
- task: AWSShellScript@1
  displayName: 'Login to ECR'
  inputs:
    awsCredentials: $(AWS_SERVICE_CONNECTION)
    regionName: $(AWS_REGION)                
    scriptType: 'inline'
    inlineScript: |
      set -euo pipefail
      
      ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      aws ecr get-login-password --region $(AWS_REGION) | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$(AWS_REGION).amazonaws.com
      echo "Login Successful!"

# 2. Build and Push Docker Image
- task: AWSShellScript@1
  displayName: 'Build and Push Image'
  inputs:
    awsCredentials: $(AWS_SERVICE_CONNECTION)
    regionName: $(AWS_REGION)
    scriptType: 'inline'
    inlineScript: |
      set -euo pipefail
      
      ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      ECR_URI="$ACCOUNT_ID.dkr.ecr.$(AWS_REGION).amazonaws.com/$(ECR_REPOSITORY_NAME)"
      
      echo "Starting Build for: $ECR_URI"
      
      cd motivational-app
      
      docker build -t $ECR_URI:$(Build.BuildId) -t $ECR_URI:latest .
      
      echo "Pushing images to ECR..."
      docker push $ECR_URI:$(Build.BuildId)
      docker push $ECR_URI:latest
      
      echo "Image pushed successfully!"