name: $(Date:yyyyMMdd)$(Rev:.r)-Release
trigger: none
pr: none

variables:
  AWS_SERVICE_CONNECTION: 'alaa-s'
  AWS_REGION: 'us-east-1'
  IMAGE_REPOSITORY: 'alaaynassar7/motivational-app'

# Pool Configuration (Self-Hosted Agent)
pool:
  name: 'Self hosted pools'
  demands:
    - Agent.Name -equals alaaynassar-VMware

jobs:
- job: Release
  displayName: 'Build and Release Docker Image'
  steps:
  - checkout: self

  # 1. Build and Push (Does not need Cluster Access)
  - task: Docker@2
    displayName: Build and Push Docker Image
    inputs:
      containerRegistry: 'alaa-docker'
      repository: $(IMAGE_REPOSITORY)
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: |
        $(Build.BuildId)
        latest