name: $(Date:yyyyMMdd)$(Rev:.r)-Tools
trigger: none
pr: none

parameters:
  - name: env
    displayName: Environment
    type: string
    default: nonprod
    values: [nonprod, prod]

variables:
  TF_DIR: 'terraform'
  TF_VAR_FILE: '${{ parameters.env }}.tfvars'
  AWS_SERVICE_CONNECTION: 'alaa-s'
  AWS_REGION: 'us-east-1'
  DATADOG_SITE: 'us5.datadoghq.com'
  TOOLS_NAMESPACE: 'alaa'

pool:
  name: 'Self hosted pools'
  demands:
    - Agent.Name -equals alaaynassar-VMware

jobs:
- job: Addons
  displayName: 'Addons Deployment (Nginx, API-GW Link, Datadog, Vault, ArgoCD, Sonar)'
  timeoutInMinutes: 160
  steps:
  - checkout: self

  - task: TerraformInstaller@1
    displayName: Install Terraform
    inputs:
      terraformVersion: latest

  - task: AWSShellScript@1
    displayName: Terraform Init & Kubeconfig
    inputs:
      awsCredentials: $(AWS_SERVICE_CONNECTION)
      regionName: $(AWS_REGION)
      scriptType: inline
      inlineScript: |
        cd "$(TF_DIR)"
        terraform init
        CLUSTER_NAME=$(terraform output -raw cluster_name || echo "")
        if [ -n "$CLUSTER_NAME" ]; then
          aws eks update-kubeconfig --name "$CLUSTER_NAME" --region "$(AWS_REGION)"
        fi

  - task: HelmInstaller@1
    displayName: Install Helm
    inputs:
      helmVersionToInstall: 'latest'

  # 1. Nginx Ingress Controller
  - task: AWSShellScript@1
    displayName: Install Nginx Ingress
    inputs:
      awsCredentials: $(AWS_SERVICE_CONNECTION)
      regionName: $(AWS_REGION)
      scriptType: inline
      inlineScript: |
        helm upgrade --install ingress-nginx ingress-nginx \
          --repo https://kubernetes.github.io/ingress-nginx \
          --namespace ingress-nginx --create-namespace \
          --set controller.service.type=LoadBalancer \
          --set controller.service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-type"="nlb" \
          --wait --timeout 15m

  # 2. Link API Gateway (Update Terraform with NLB Info)
  - task: AWSShellScript@1
    displayName: Sync API Gateway & Cognito
    inputs:
      awsCredentials: $(AWS_SERVICE_CONNECTION)
      regionName: $(AWS_REGION)
      scriptType: inline
      inlineScript: |
        cd "$(TF_DIR)"
        NLB_DNS=$(kubectl get svc -n ingress-nginx ingress-nginx-controller -o jsonpath='{.status.loadBalancer.ingress[0].hostname}' || echo "")
        if [ -n "$NLB_DNS" ]; then
          NLB_NAME=$(echo $NLB_DNS | cut -d'-' -f1)
          LB_ARN=$(aws elbv2 describe-load-balancers --region $(AWS_REGION) --names "$NLB_NAME" --query 'LoadBalancers[0].LoadBalancerArn' --output text)
          LISTENER_ARN=$(aws elbv2 describe-listeners --region $(AWS_REGION) --load-balancer-arn "$LB_ARN" --query 'Listeners[0].ListenerArn' --output text)
          terraform apply -auto-approve -var-file="$(TF_VAR_FILE)" -var="nlb_listener_arn=$LISTENER_ARN"
        fi

  # 3. Datadog (Secret Key is hidden in Variables)
  - task: AWSShellScript@1
    displayName: Install Datadog
    inputs:
      awsCredentials: $(AWS_SERVICE_CONNECTION)
      regionName: $(AWS_REGION)
      scriptType: inline
      inlineScript: |
        helm repo add datadog https://helm.datadoghq.com
        helm repo update
        helm upgrade --install datadog-agent datadog/datadog \
          --namespace $(TOOLS_NAMESPACE) --create-namespace \
          --set datadog.apiKey=$(DATADOG_API_KEY) \
          --set datadog.site=$(DATADOG_SITE) \
          --set datadog.logs.enabled=true \
          --set datadog.logs.containerCollectAll=true

  # 4. Vault (HashiCorp)
  - task: AWSShellScript@1
    displayName: Install Vault
    inputs:
      awsCredentials: $(AWS_SERVICE_CONNECTION)
      regionName: $(AWS_REGION)
      scriptType: inline
      inlineScript: |
        helm upgrade --install vault vault --repo https://helm.releases.hashicorp.com \
          --namespace $(TOOLS_NAMESPACE) \
          --set server.ingress.enabled=true \
          --set server.ingress.ingressClassName=nginx \
          --set server.ingress.hosts[0].host="" \
          --set server.ingress.hosts[0].paths[0]="/vault"

  # 5. ArgoCD
  - task: AWSShellScript@1
    displayName: Install ArgoCD
    inputs:
      awsCredentials: $(AWS_SERVICE_CONNECTION)
      regionName: $(AWS_REGION)
      scriptType: inline
      inlineScript: |
        helm upgrade --install argocd argo-cd --repo https://argoproj.github.io/argo-helm \
          --namespace $(TOOLS_NAMESPACE) \
          --set server.extraArgs={--insecure,--rootpath=/argocd} \
          --set server.ingress.enabled=true \
          --set server.ingress.ingressClassName=nginx \
          --set server.ingress.hosts[0]="" \
          --set server.ingress.paths[0]="/argocd"

  # 6. SonarQube
  - task: AWSShellScript@1
    displayName: Install SonarQube
    inputs:
      awsCredentials: $(AWS_SERVICE_CONNECTION)
      regionName: $(AWS_REGION)
      scriptType: inline
      inlineScript: |
        helm upgrade --install sonarqube sonarqube --repo https://SonarSource.github.io/helm-chart-sonarqube \
          --namespace $(TOOLS_NAMESPACE) \
          --set sonarWebContext=/sonarqube \
          --set ingress.enabled=true \
          --set ingress.ingressClassName=nginx \
          --set ingress.hosts[0].name="" \
          --set ingress.hosts[0].path=/sonarqube