apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  labels:
    {{- include "motivational-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  # Database Credentials used by MongoDB Deployment
  MONGO_ROOT_USERNAME: "root"
  MONGO_ROOT_PASSWORD: "password123"
  
  # Connection String used by Flask App
  # Format: mongodb://username:password@service-name:port/db_name?authSource=admin
  MONGO_URI: "mongodb://root:password123@mongodb:27017/motivational_db?authSource=admin"